spring.application.name=CommandLineRunnerTest
dva.ecm.application.id=CommandLineRunnerTest
# taxonomy data source
com.davita.jpa.taxonomycfg.datasource.driver-class-name=oracle.jdbc.OracleDriver
com.davita.jpa.taxonomycfg.datasource.jdbcUrl=jdbc:oracle:thin:@sea1l3p8dbd01.davita.corp:1533:ECMDEV2
com.davita.jpa.taxonomycfg.datasource.username=svc_ecm_appconfig_np
com.davita.jpa.taxonomycfg.datasource.password=ENC(5Z0wJ0EM25aXs/2pfVILIH+iaGs37RZxwySxzbqMFQI=)

dva.ecm.authentication.none=true

jasypt.encryptor.password=${JASYPT_PASSWORD}
